Eye_Tracking_Constants:
  FOVEAL_REGION_RADIUS: 41
  PARAFOVEAL_REGION_RADIUS: 185
  MIN_FIXATION_TIME_THRESHOLD: 113

Our_approach_constants:
  ERROR_REGION: 82
  NEXT_WORD_DISTANCE_THRESHOLD: 4
  MIN_WORDS_FOR_READING_SEQUENCE: 3

Cole2011_constants:
  MIN_FIXATION_COUNT_THRESHOLD: 4